version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "10:00"
      timezone: America/Vancouver
    groups:
      github-actions-minor-patch:
        update-types:
          - minor
          - patch
    open-pull-requests-limit: 5

  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "10:30"
      timezone: America/Vancouver
    groups:
      go-modules-minor-patch:
        update-types:
          - minor
          - patch
    open-pull-requests-limit: 5
